# 函数
## 常用函数
不同DBMS有不同的函数的名称和语法，所以在使用函数时做好注释。

- 提取字符串的组成部分：`SUBSTRING()`。

- 数据类型转换：`CONVERT()`。

- 取当前日期：`CURDATE()`。

## 文本处理函数

| 函数 | 说明 |
| --- | --- |
| `LEFT()`（或使用子字符串函数） | 返回字符串左边的字符 |
| `LENGTH()`（也使用 DATALENGTH() 或 LEN()） | 返回字符串的长度 |
| `LOWER()` | 将字符串转换为小写 |
| `LTRIM()` | 去掉字符串左边的空格 |
| `RIGHT()`（或使用子字符串函数） | 返回字符串右边的字符 |
| `RTRIM()` | 去掉字符串右边的空格 |
| `SUBSTRING()` | 提取字符串的组成部分 |
| `SOUNDEX()` | 返回字符串的 SOUNDEX 值 |
| `UPPER()` | 将字符串转换为大写 |

- SOUNDEX 是一个将任何文本串转换为描述其语音表示的字母数字模式的算法。

```{sql, connection = conn}
SELECT cust_name, cust_contact
FROM Customers
WHERE SOUNDEX(cust_contact) = SOUNDEX('Michael Green');
-- Michael Green 和 Michelle Green 发音相似
```

## 日期和时间处理函数
- `YEAR()` 函数从日期中提取年份。

```{sql, connection = conn}
SELECT order_num, order_date
FROM Orders
WHERE YEAR(order_date) = 2020;
```

## 数值处理函数


函数 | 说明
| --- | --- |
`ABS()` | 返回一个数的绝对值
`COS()` | 返回一个角度的余弦
`EXP()` | 返回一个数的指数值
`PI()` | 返回圆周率 π 的值
`SIN()` | 返回一个角度的正弦
`SQRT()` | 返回一个数的平方根
`TAN()` | 返回一个角度的正切

## 练习
1. 我们的商店已经上线了，正在创建顾客账户。所有用户都需要登录名，默认登录名是其名称和所在城市的组合。编写 SQL 语句，返回顾客 ID（cust_id）、顾客名称（customer_name）和登录名（user_login），其中登录名全部为大写字母，并由顾客联系人的前两个字符（cust_contact）和其所在城市的前三个字符（cust_city）组成。例如，我的登录名是 BEOAK（Ben Forta，居住在 Oak Park）。提示：需要使用函数、拼接和别名。

```{sql, connection = conn}
SELECT cust_id, cust_name,
  UPPER( CONCAT(
          SUBSTRING(cust_contact, 1, 2),
          SUBSTRING(cust_city, 1, 3) 
          )
        ) AS user_login
FROM Customers;
```

2. 编写 SQL 语句，返回 2020 年 1 月的所有订单的订单号（order_num）和订单日期（order_date），并按订单日期排序。你应该能够根据目前已学的知识来解决此问题，但也可以开卷查阅 DBMS 文档。

```{sql, connection = conn}
SELECT order_num, order_date
FROM Orders
WHERE YEAR(order_date) = 2020 AND MONTH(order_date) = 01
ORDER BY order_date;
```

